version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - 2020.0.2-SNAPSHOT
    - 2020.0.3-SNAPSHOT
    - 2020.1.0-SNAPSHOT
  - dependency-name: org.axonframework:axon-test
    versions:
    - 4.4.6
    - 4.4.7
    - 4.4.8
  - dependency-name: org.axonframework:axon-spring-boot-starter
    versions:
    - 4.4.6
    - 4.4.7
    - 4.4.8
